//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARAcademy.model.classmeeting {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DAOClassMeetingResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DAOClassMeetingResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ARAcademy.model.classmeeting.DAOClassMeetingResource", typeof(DAOClassMeetingResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @agendazoom.
        /// </summary>
        internal static string Agenda {
            get {
                return ResourceManager.GetString("Agenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @comentario.
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREATE_CLASS.
        /// </summary>
        internal static string CreateClassSP {
            get {
                return ResourceManager.GetString("CreateClassSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @fec_creacion.
        /// </summary>
        internal static string CreationDate {
            get {
                return ResourceManager.GetString("CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DELETE_CLASS.
        /// </summary>
        internal static string DeleteClassSP {
            get {
                return ResourceManager.GetString("DeleteClassSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @duracion.
        /// </summary>
        internal static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @email_host.
        /// </summary>
        internal static string EmailHost {
            get {
                return ResourceManager.GetString("EmailHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @ide.
        /// </summary>
        internal static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @ide_host.
        /// </summary>
        internal static string IdHost {
            get {
                return ResourceManager.GetString("IdHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @clave.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @clave_encriptada.
        /// </summary>
        internal static string PasswordEncrypted {
            get {
                return ResourceManager.GetString("PasswordEncrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @clave_h323.
        /// </summary>
        internal static string PasswordH323 {
            get {
                return ResourceManager.GetString("PasswordH323", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @clave_pstn.
        /// </summary>
        internal static string PasswordPSTN {
            get {
                return ResourceManager.GetString("PasswordPSTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a READ_ALL_CLASS.
        /// </summary>
        internal static string ReadAllClassesSP {
            get {
                return ResourceManager.GetString("ReadAllClassesSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a READ_CLASS.
        /// </summary>
        internal static string ReadClassSP {
            get {
                return ResourceManager.GetString("ReadClassSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @link_reunion.
        /// </summary>
        internal static string ReunionLink {
            get {
                return ResourceManager.GetString("ReunionLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @fk_seccion.
        /// </summary>
        internal static string Section {
            get {
                return ResourceManager.GetString("Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @link_inicio.
        /// </summary>
        internal static string StartLink {
            get {
                return ResourceManager.GetString("StartLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @estado.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @fk_profesor.
        /// </summary>
        internal static string Teacher {
            get {
                return ResourceManager.GetString("Teacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @zonahoraria.
        /// </summary>
        internal static string Timezone {
            get {
                return ResourceManager.GetString("Timezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @topico.
        /// </summary>
        internal static string Topic {
            get {
                return ResourceManager.GetString("Topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @tipo.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UPDATE_CLASS_COMMENT.
        /// </summary>
        internal static string UpdateClassCommentSP {
            get {
                return ResourceManager.GetString("UpdateClassCommentSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UPDATE_CLASS.
        /// </summary>
        internal static string UpdateClassSP {
            get {
                return ResourceManager.GetString("UpdateClassSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @ideuu.
        /// </summary>
        internal static string uuId {
            get {
                return ResourceManager.GetString("uuId", resourceCulture);
            }
        }
    }
}
