//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARAcademy.model.report {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DAOReportResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DAOReportResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ARAcademy.model.report.DAOReportResource", typeof(DAOReportResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a COUNT_STUDENTS_BY_SECTION_PERIOD.
        /// </summary>
        internal static string CountStundentsBySectionPeriodSP {
            get {
                return ResourceManager.GetString("CountStundentsBySectionPeriodSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @fechafin.
        /// </summary>
        internal static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @ide.
        /// </summary>
        internal static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @fechaini.
        /// </summary>
        internal static string IniDate {
            get {
                return ResourceManager.GetString("IniDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PAYMENTS_LIST_BY_SECTION.
        /// </summary>
        internal static string PaymentListBySectionSP {
            get {
                return ResourceManager.GetString("PaymentListBySectionSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PAYMENTS_LIST.
        /// </summary>
        internal static string PaymentListSP {
            get {
                return ResourceManager.GetString("PaymentListSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PAYMENTS_COUNT.
        /// </summary>
        internal static string PaymentsCountSP {
            get {
                return ResourceManager.GetString("PaymentsCountSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a READ_CLASS_BY_TEACHER_PERIOD.
        /// </summary>
        internal static string ReadClassByTeacherPeriodSP {
            get {
                return ResourceManager.GetString("ReadClassByTeacherPeriodSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a READ_STUDENTS_BY_SECTION_PERIOD.
        /// </summary>
        internal static string ReadStudentsBySectionPeriodSP {
            get {
                return ResourceManager.GetString("ReadStudentsBySectionPeriodSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @fk_profesor.
        /// </summary>
        internal static string TeacherId {
            get {
                return ResourceManager.GetString("TeacherId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TOTAL_HOURS_TEACHER.
        /// </summary>
        internal static string TotalHoursTeacher {
            get {
                return ResourceManager.GetString("TotalHoursTeacher", resourceCulture);
            }
        }
    }
}
