//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARAcademy.model.payment {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DAOPaymentResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DAOPaymentResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ARAcademy.model.payment.DAOPaymentResource", typeof(DAOPaymentResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @monto.
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        internal static string AvailableClasses {
            get {
                return ResourceManager.GetString("AvailableClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE_PAYMENT.
        /// </summary>
        internal static string CreatePaymentSP {
            get {
                return ResourceManager.GetString("CreatePaymentSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE_PAYMENT.
        /// </summary>
        internal static string DeletePaymentSP {
            get {
                return ResourceManager.GetString("DeletePaymentSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @fechaexpiracion.
        /// </summary>
        internal static string ExpirationDate {
            get {
                return ResourceManager.GetString("ExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ide.
        /// </summary>
        internal static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @diapago.
        /// </summary>
        internal static string PaymentDate {
            get {
                return ResourceManager.GetString("PaymentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @paypal_id.
        /// </summary>
        internal static string PaypalTransactionID {
            get {
                return ResourceManager.GetString("PaypalTransactionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to READ_ALL_PAYMENT.
        /// </summary>
        internal static string ReadAllPaymentsSP {
            get {
                return ResourceManager.GetString("ReadAllPaymentsSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to READ_PAYMENT_BY_STUDENT.
        /// </summary>
        internal static string ReadPaymentByStudentSP {
            get {
                return ResourceManager.GetString("ReadPaymentByStudentSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to READ_PAYMENT_BY_SECION.
        /// </summary>
        internal static string ReadPaymentsBySectionSP {
            get {
                return ResourceManager.GetString("ReadPaymentsBySectionSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to READ_PAYMENT.
        /// </summary>
        internal static string ReadPaymentSP {
            get {
                return ResourceManager.GetString("ReadPaymentSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @clasesrestantes.
        /// </summary>
        internal static string RemainingClasses {
            get {
                return ResourceManager.GetString("RemainingClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @fk_seccion.
        /// </summary>
        internal static string SectionID {
            get {
                return ResourceManager.GetString("SectionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @fk_estudiante.
        /// </summary>
        internal static string StudentID {
            get {
                return ResourceManager.GetString("StudentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE_REMAINING_CLASSES.
        /// </summary>
        internal static string UpdateClassesSP {
            get {
                return ResourceManager.GetString("UpdateClassesSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE_PAYMENT.
        /// </summary>
        internal static string UpdatePaymentSP {
            get {
                return ResourceManager.GetString("UpdatePaymentSP", resourceCulture);
            }
        }
    }
}
