//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARAcademy.model.offer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DAOOfferResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DAOOfferResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ARAcademy.model.offer.DAOOfferResource", typeof(DAOOfferResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE_OFFER.
        /// </summary>
        internal static string CreateOfferSP {
            get {
                return ResourceManager.GetString("CreateOfferSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE_OFFER.
        /// </summary>
        internal static string DeleteOfferSP {
            get {
                return ResourceManager.GetString("DeleteOfferSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @descripcion.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @fechafin.
        /// </summary>
        internal static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ide.
        /// </summary>
        internal static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @fechaini.
        /// </summary>
        internal static string InitDate {
            get {
                return ResourceManager.GetString("InitDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @articulos_min.
        /// </summary>
        internal static string MinArticles {
            get {
                return ResourceManager.GetString("MinArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @nombre.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @porcentaje.
        /// </summary>
        internal static string Percentage {
            get {
                return ResourceManager.GetString("Percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to READ_ACTIVE_OFFER.
        /// </summary>
        internal static string ReadActiveOfferSP {
            get {
                return ResourceManager.GetString("ReadActiveOfferSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to READ_OFFER_BY_DATE.
        /// </summary>
        internal static string ReadOfferByDateSP {
            get {
                return ResourceManager.GetString("ReadOfferByDateSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to READ_OFFER_BY_ID.
        /// </summary>
        internal static string ReadOfferByIdSP {
            get {
                return ResourceManager.GetString("ReadOfferByIdSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to READ_OFFERS.
        /// </summary>
        internal static string ReadOffersSP {
            get {
                return ResourceManager.GetString("ReadOffersSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE_OFFER.
        /// </summary>
        internal static string UpdateOfferSP {
            get {
                return ResourceManager.GetString("UpdateOfferSP", resourceCulture);
            }
        }
    }
}
