//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARAcademy.model.educate {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DAOEducateResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DAOEducateResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ARAcademy.model.educate.DAOEducateResource", typeof(DAOEducateResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE_EDUCATE.
        /// </summary>
        internal static string CreateEducateSP {
            get {
                return ResourceManager.GetString("CreateEducateSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE_EDUCATE.
        /// </summary>
        internal static string DeleteEducateSP {
            get {
                return ResourceManager.GetString("DeleteEducateSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ide.
        /// </summary>
        internal static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to READ_EDUCATE_BY_TEACHER_EMAIL.
        /// </summary>
        internal static string ReadEducateByTeacherEmailSp {
            get {
                return ResourceManager.GetString("ReadEducateByTeacherEmailSp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to READ_TEACHER_BY_SECTION_ID.
        /// </summary>
        internal static string ReadTeacherBySectionIdSP {
            get {
                return ResourceManager.GetString("ReadTeacherBySectionIdSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @fk_seccion.
        /// </summary>
        internal static string SectionID {
            get {
                return ResourceManager.GetString("SectionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @fk_profesor.
        /// </summary>
        internal static string TeacherID {
            get {
                return ResourceManager.GetString("TeacherID", resourceCulture);
            }
        }
    }
}
